# Generated by Django 5.0.6 on 2024-07-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_users_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='otp_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
