# Generated by Django 4.2.6 on 2024-07-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
