# Generated by Django 4.2.6 on 2024-07-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.TextField()),
                ('emp_designation', models.CharField(choices=[('JD', 'Junior Developer'), ('SD', 'Senior Developer'), ('FSD', 'Full Stack Developer'), ('BD', 'Backend Developer'), ('FD', 'Frontend Developer'), ('HR', 'HR'), ('UIUX', 'UI/UX Developer'), ('ACC', 'Accounting')], max_length=4)),
                ('emp_qualification', models.CharField(max_length=50)),
                ('emp_salary', models.IntegerField()),
            ],
        ),
    ]
