# Generated by Django 4.2.6 on 2024-07-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_employees_employee_email_employees_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employee_email',
            field=models.EmailField(max_length=254),
        ),
    ]
